// <auto-generated />
namespace WebMvc5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class adddeparmentid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddeparmentid));
        
        string IMigrationMetadata.Id
        {
            get { return "202102010927021_adddeparmentid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
