[
    {
       "id":1, 
       "text":"西南石油局",
        "state":"closed",
        "children":[{"text":"华星天然气公司"},{"text":"川渝石油基地服务中心"}]
    }
   ,{
       "id":2,        
         "text":"西南油气分公司",
        "state":"open",
        "children":[
           {"text":"川西采气厂","checked":true},
           {"text":"川东北采气厂"},
           {"text":"石油工程监督中心"},
           {"text":"油气销售中心"},
           {"text":"物资供应中心"}
        ]
    }
   ,{
        "id":3,        
        "text":"西南石油工程公司",
        "state":"closed",
        "children":[{"text":"地质录井公司"},{"text":"测井公司"}]
    }
   ,{
       "id":4,        
         "text":"中石化外部单位",
        "state":"closed",
        "children":[
           {"text":"中原油建"},
           {"text":"仁智公司"},
           {"text":"胜利钻井"}
        ]
    }
]